### ISSUE TITLE
tv problem

### ISSUE THREAD

**Issue by kenneth1516** [PickleModifications/ptelevision#2] opened 2022-11-15 05:02 UTC
What ever is played on one tv plays on the other ones!

**Comment by anes66** [comment] 2022-11-24 02:29
can confirm the same problem i think on all tv itd play the same

**Comment by PickleModifications** [comment] 2022-11-25 06:56
Use Version 1.2+

**Comment by anes66** [comment] 2022-11-25 19:48
i have also the latest version but same problem

**Comment by kenneth1516** [comment] 2022-11-26 05:18
yeah still playing on all tvs

**Comment by PickleModifications** [comment] 2022-12-03 04:32
Fixed on version v1.2.0.

**Closed by PickleModifications** 2022-12-03 04:32 UTC

**Comment by FelixDE** [comment] 2023-02-18 21:56
Unfortunately the problem isn't fixed yet. If you turn on something on one TV and then go to others that haven't been used before, the same thing happens there.
